### ISSUE TITLE
i got a problem

### ISSUE THREAD

**Issue by kimkim2212** [g7/sailfishx-patcher-f5321#1]
when i start final instruction

i got a error

kim@ubuntu:~/sailfishx-patcher-f5321$ vagrant ssh -c "/vagrant/patch.sh -a f5321 -i /vagrant/Sailfish*.zip"
W: You must be root to use this script! Trying with sudo...
I: Unzipping the Sailfish X archive
Archive:  /vagrant/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /vagrant/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of /vagrant/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13.zip or
        /vagrant/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13.zip.zip, and cannot find /vagrant/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13.zip.ZIP, period.
I: Cleaning up...

plz hepl me

**Comment by kimkim2212** [comment]
i solve it. i use virtual machine and copy the image file. but this procudure makes image file crash. so i download in ubuntu directle. thanks!

**Comment by kimkim2212** [comment]
i did all instuction but i can get patched new file. it is right that just same file that i downloaded??

or new file is created?? 

if i can't get a new file i have some problem?? look my log

kim@ubuntu:~/sailfishx-patcher-f5321$ vagrant ssh -c "/vagrant/patch.sh -a f5321 -i /vagrant/Sailfish*.zip"
W: You must be root to use this script! Trying with sudo...
I: Unzipping the Sailfish X archive
Archive:  /vagrant/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13.zip
   creating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/os-release  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/flash-on-windows.bat  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/fastboot.exe  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/fastboot.img  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/flashing-README.txt  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/hybris-boot.img  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/AdbWinUsbApi.dll  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/hybris-recovery.img  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/md5.lst  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/fimage.img001  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/flash.sh  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/Jolla-2.2.1.18-f5121-armv7hl.urls  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/hw-release  
  inflating: /tmp/sailfish-image-patcher/Sailfish_OS-Jolla-2.2.1.18-f5121-0.2.1.13/AdbWinApi.dll  
I: Converting the fimage sparse image to a raw image...
Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.

i work on ubuntu 14.0.4 / lastet version of vagrant and virtualbox

**Comment by g7** [comment]
Hello,

If everything went correctly, a new .zip is created.

How much RAM do you have? I guess that simg2img (the command executed in the "Converting the fimage sparse image to a raw image") crashed due to lack of RAM.

**Comment by kimkim2212** [comment]
my coputer is 4gb and i use 2gb on virtual machine.

**Comment by kimkim2212** [comment]
oh. !! i solve it. i increase my ram for virtual machine and it works. Thanks.!! your my hero.

**Comment by g7** [comment]
Great! Glad that it worked. Enjoy!
