### ISSUE TITLE
SailfishX 3.2.0.12 patched image flash failed

### ISSUE THREAD

**Issue by TiceRex** [g7/sailfishx-patcher-f5321#10]
The patch seems to be working properly (see attached patch.log), but the resulting image cannot be flashed (see flash.log).
Advice please!

The previous version (3.1.0.11) was working properly, but the OTA update to 3.2.0.12 breaks the Android support (Android support can be installed, but Aptoide fails). I'm not sure if it's related to the patched image or not.

[patch.log](https://github.com/g7/sailfishx-patcher-f5321/files/3825888/patch.log)
[flash.log](https://github.com/g7/sailfishx-patcher-f5321/files/3825891/flash.log)

**Comment by teleshoes** [comment]
i can second BOTH of these symptoms, but whats more, android app support continues to be broken when i flash back to 3.1, despite it working after flashing 3.1 the first time

**Comment by g7** [comment]
Hello,

Could you please try repatching the image using the patcher from the `block-size-alignment` branch?

You can switch to the branch by running

    git fetch origin
    git checkout block-size-alignment

and then running the patcher as always by running

    vagrant ssh -c "/vagrant/patch.sh -a f5321 -i /vagrant/Sailfish*.zip"

I haven't tested on-device as I don't have a spare X Compact, but it should at least flash correctly.

@teleshoes @TiceRex if the issue regarding aliendalvik is Aptoide, I think that's a known bug and outside this patch's scope: https://together.jolla.com/question/216292/bug-android-store-gets-updated-to-applicaciones-market/?answer=216359#post-id-216359

**Comment by teleshoes** [comment]
i will test on device now and report back.

as for aliendalvik issue, its not the same issue (i had that issue as well a few _days_ ago). installing the android store is broken, yes, but it just fails completely to install. no desktop file is created, so icon disappears.
also, installing any APK (with apkd-install) fails silently, whereas it used to work right out of the box.
literally no android UIs ever come up, when launching any intents or apkd-launcher or anything.

**Comment by g7** [comment]
Hmmm, perhaps is some SELinux-related issue? Do the cameras and flashlight work?

**Comment by teleshoes** [comment]
hmm, hadnt checked that, and now im reflashing. successfully btw, so thanks for that!

**Comment by teleshoes** [comment]
also note, re: android, that a newly patched 3.1 zip file also demonstrates this issue.

it doesnt matter if its installed from RPM without jolla login, or with a valid SFOS license during the initial setup, or with a valid SFOS license from the store after install or with 3.1 vs 3.2 (i tried all combinations of the above jic).

**Comment by teleshoes** [comment]
hahahah, android problem is GONE when i flash from the newly created 3.2.0.12 zip

thanks so much!

**Comment by g7** [comment]
Great! Thanks for testing :)

Still can't wrap my head on why aliendalvik didn't work on 3.1, but what's important is that it works now :)

Merging on `master` and closing this issue.

**Comment by henning-schild** [comment]
For me the update went smoothly. @g7 would you suggest to reflash/repatch some day to avoid problems in the future? Maybe the alignment is ok on my device, i guess i could somehow check that. Any suggestions?

**Comment by g7** [comment]
@henning-schild no, existing installations are fine, don't worry about that. OTA upgrades get the same fixes newly patched images do (except this one, but is a non-issue as previous releases were properly aligned anyways).

I haven't actually reflashed my X Compact since 2.1.3 😄
