### ISSUE TITLE
Valid metadata not found at specified URL(s)

### ISSUE THREAD

**Issue by tltow** [g7/sailfishx-patcher-f5321#2]
When patching the original sailfish-image (2.2.1.18) i get a few errors, but in the end i have a patched image i can install and use on my device (Xperia X Compact). I am still struggling to get the fingerprint reader to work. Any hints what can cause this, or can i simply ignore this?

Retrieving repository 'tmp-compat-f5321' metadata ...........................................................................................................[done]
Building repository 'tmp-compat-f5321' cache ................................................................................................................[done]
Specified repositories have been refreshed.
Retrieving repository 'jolla' metadata ......................................................................................................................[done]
Building repository 'jolla' cache ...........................................................................................................................[done]
Specified repositories have been refreshed.
Error building the cache:
[|] Valid metadata not found at specified URL(s)
Warning: Disabling repository 'adaptation0' because of the above error.
Error building the cache:
[|] Valid metadata not found at specified URL(s)
Warning: Disabling repository 'adaptation1' because of the above error.
Error building the cache:
[|] Valid metadata not found at specified URL(s)
Warning: Disabling repository 'aliendalvik' because of the above error.
Building repository 'apps' cache ............................................................................................................................[done]
Building repository 'customer-jolla' cache ..................................................................................................................[done]
Building repository 'hotfixes' cache ........................................................................................................................[done]
Building repository 'jolla' cache ...........................................................................................................................[done]
Error building the cache:
[|] Valid metadata not found at specified URL(s)
Warning: Disabling repository 'sailfish-eas' because of the above error.
Building repository 'tmp-compat-f5321' cache ................................................................................................................[done]
Error building the cache:
[|] Valid metadata not found at specified URL(s)
Warning: Disabling repository 'xt9' because of the above error.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

**Comment by g7** [comment]
Hello,

those "Valid metadata not found at specified URLs" can be ignored. Those repositories (adaptation0, adaptation1, aliendalvik, etc) require authentication (valid Jolla account with Sailfish X license) so they're skipped during the patching phase.

If it flashes and boots correctly (with the right scaling settings and all), the patch went in successfully.

Did the Fingerprint sensor work correctly in Android? You can also use the CSD Tool to test the hardware on the phone. You can open it by opening Settings -> About product and then by tapping repeatedly on the "Build" label.

Then go to Individual tests -> Fingerprint sensor

**Comment by tltow** [comment]
Thank you for making this clear. 

Checking the sensor using the CSD Tool ist not possible since the test already fails upon verifiying the sensor :-(
I never used the original android on this phone. Until flashing flashing sailfish i was using omnirom where i was also unable to use the sensor. It was impossible to register fingerprints, but the sensor was detected and responsive.
There are also other CSD Tool tests failing, like the proximity sensor, gyro & acclerometer and compass.

I will dig deeper into these issues, when i find the time to do this :-)

**Comment by g7** [comment]
Sorry for my late reply - overlooked my notifications.

Hope you found out in the end if it was actually an hardware issue :) gyro & compass are disabled by default in the patch (see the FAQ section) but definitely the other sensor should work fine by default.
