### ISSUE TITLE
storage encryption pinpad has large font

### ISSUE THREAD

**Issue by henning-schild** [g7/sailfishx-patcher-f5321#25]
when i last reflashed my compact i decided to go for storage encryption, that introduced a new screen before device pin and sim pin need to be entered on boot. That pinpad hardly fits on the screen and has some overlapping going on.

I assume there must be some qml/css which needs a device specific size reduction for the compact.

Is anyone else also seeing that issue? Does anyone have a clue on what to look out for, to possibly patch my already flashed device and throw a patch on this repo?

**Comment by g7** [comment]
Perhaps they've changed scaling handling again :) Could you post the output of

```
ls -ltha /usr/share/sailfish-minui/images/
```

**Comment by henning-schild** [comment]
```
total 16K    
drwxr-xr-x    2 root     root        4.0K Sep 18 08:30 z1.25
drwxr-xr-x    2 root     root        4.0K Sep 18 08:30 z1.75
drwxr-xr-x    3 root     root        4.0K Aug  6 06:19 ..
drwxr-xr-x    4 root     root        4.0K Jun 20 20:52 .
lrwxrwxrwx    1 root     root          38 May 20 13:35 default -> /usr/share/sailfish-minui/images/z1.75

```

**Comment by g7** [comment]
Ok, so they seemingly didn't change anything - but for some reason the default symlink is still pointing to the wrong place (should go to `z1.25`)

What does `systemctl status droid-compat-f5321-fix-minui-defaults` say?

**Comment by henning-schild** [comment]
```
Unit droid-compat-f5321-fix-minui-defaults.service could not be found.
```

Which package should that be coming from?

**Comment by henning-schild** [comment]
Could i just correct that symlink manually?

**Comment by henning-schild** [comment]
Ok the package `droid-compat-f5321-droid-config-sailfih` brings `/lib/systemd/system/droid-compat-f5321-fix-minui-defaults.service` which should probably be living in `usr/lib/systemd/system` instead, maybe recent version changed the location

**Comment by henning-schild** [comment]
will send a patch, manual move worked
