### ISSUE TITLE
camera not working on  sfos 4.3

### ISSUE THREAD

**Issue by smatkovi** [g7/sailfishx-patcher-f5321#26]
i patched my mother's  x compact and updated it to the newest version of sailfish  os and now she says that the camera isn't working. i will look into it on Tuesday, but maybe someone has an idea or to warn you from upgrading. i will try the answer to the last issue  regarding  sfos 4.1

**Comment by henning-schild** [comment]
did it work before? I am on Verla (4.2) which was patched/flashed and did not go through any OTA yet. Now i am kind of shy to try that OTA ;).

**Comment by henning-schild** [comment]
Please drop logs and possible debug info here when you get access to the device. Not sure what would count, maybe `lsmod`, `ls -al /dev` and whatever the/a camera using app spits out on cmdline launch.

**Comment by smatkovi** [comment]
she was on 3.4 and  yes it worked before

**Comment by smatkovi** [comment]
[nemo@Sailfish ~]$ LC_ALL=C harbour-advanced-camera
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Scanning "/media/sdcard"
[D] unknown:0 - Storage: "Internal storage" "/home/nemo"
[D] unknown:0 - Storage: "027e2333-fd79-4f05-8820-9ce44cbef999" "
/media/sdcard/027e2333-fd79-4f05-8820-9ce44cbef999"
[W] unknown:0 - Theme dir "/usr/share/themes/jolla/meegotouch/z1.
25/" does not exist
harbour-advanced-camera: /usr/share/droidmedia/hybris.c:53: __res
olve_sym: Assertion `ptr != NULL' failed.
Aborted (core dumped)

**Comment by smatkovi** [comment]
[devlist.txt](https://github.com/g7/sailfishx-patcher-f5321/files/7548509/devlist.txt)

**Comment by smatkovi** [comment]
[dmesgout.txt](https://github.com/g7/sailfishx-patcher-f5321/files/7548514/dmesgout.txt)

**Comment by g7** [comment]
Do you have aliendalvik installed? And, if so, does the camera work there?

It looks like that droidmedia is not actually getting loaded... could you:

1) Run advanced camera (or jolla-camera as well) through `strace` and post the output there
3) Ensure that the repositories are pointing to the correct sailfish version:

```
ssu re 4.3.0.12
pkcon refresh
```

3) Post the output of `ssu lr`
4) Post the output of `pkcon search name droid-system-f5121`

**Comment by smatkovi** [comment]
lol in telegram  x for  android  it really works

**Comment by smatkovi** [comment]
[nemo@Sailfish ~]$     pkcon search name droid-system-f5121
Suche nach Name
Starten
Software-Liste wird aktualisiert
Abfragen
Fertig
Installiert     droid-system-f5121-0.4.2-1.2.2.jolla.armv7hl (ins
talled)         Built from source /system for Droid HAL adaptatio
ns
[nemo@Sailfish ~]$

**Comment by smatkovi** [comment]
[Uploading straceJollaCameraErrors.txt…](
[ssuLr.txt](https://github.com/g7/sailfishx-patcher-f5321/files/7548955/ssuLr.txt)
)

**Comment by smatkovi** [comment]
[ssuLr.txt](https://github.com/g7/sailfishx-patcher-f5321/files/7548956/ssuLr.txt)

**Comment by smatkovi** [comment]
[straceJollaCameraErrors.txt](https://github.com/g7/sailfishx-patcher-f5321/files/7548957/straceJollaCameraErrors.txt)

**Comment by smatkovi** [comment]
i wanted to patch sfos 4.2 but  then  i decided to install her open camera the android app and this is working

**Comment by g7** [comment]
You said it was on 3.4 before, did you upgrade to 4.3 (including the eventual stop releases) or did you patch a new image and then reflashed the devie?

Camera apps in aliendalvik work since they use the android camera hal directly rather than going through droidmedia

**Comment by smatkovi** [comment]
i upgraded through stop releases in settings

**Comment by g7** [comment]
Could you run

```
HYBRIS_TRACE=1 HYBRIS_TRACE_UNHOOKED=1 HYBRIS_TRACE_HOOKED=1 jolla-camera
```

and post the output here?

**Comment by smatkovi** [comment]
[nemo@Sailfish ~]$ HYBRIS_TRACE=1 HYBRIS_TRACE_UNHOOKED=1 HYBRIS_
TRACE_HOOKED=1 jolla-camera
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Theme dir "/usr/share/themes/jolla/meegotouch/z1.
25/" does not exist
jolla-camera: /usr/share/droidmedia/hybris.c:53: __resolve_sym: Z
usicherung »ptr != NULL« nicht erfüllt.
Aborted (core dumped)
[nemo@Sailfish ~]$

**Comment by g7** [comment]
Damn, I think that Jolla-provided images do not have hybris tracing enabled :(

Anyways, I asked someone I know to check on their spare X Compact that got recently updated to 4.3  if the camera is working, will let you know...

According to the strace above libdroidmedia exists and gets loaded, it fails later when trying to load a symbol, perhaps there is either mismatch somewhere between the loader in the glibc side and what's it's actually in the android HAL parts. It's curious since this stuff is not touched at all by the compatibility layer

**Comment by smatkovi** [comment]
i was  stupid, i tried downgrading with  ssu. now the browser isn't working. but  i should be able to remove it and install it again with  zypper. it downloaded the "downgrade" but didn't install anything

**Comment by smatkovi** [comment]
okay it  was just the network connection, not the browser

**Comment by henning-schild** [comment]
the way i read this seems to suggest that i should probably not yet update my device, because it is my daily driver and it seems likely i would break the native camera support as well. Is that assumption correct?

**Comment by g7** [comment]
> Anyways, I asked someone I know to check on their spare X Compact that got recently updated to 4.3 if the camera is working, will let you know...

Ok, got a reply, stock jolla-camera works fine on their device so perhaps the upgrade went wrong somehow ?! Did you upgrade via UI or via zypper/version/sfos-upgrade?

**Comment by smatkovi** [comment]
oh good news then. if  i remember correctly  via ui

**Comment by oh1jty** [comment]
Same problem here. Camera worked fine with 2.x, 3.x, but with latest Suomenlinna it fails to start.
"[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Scanning "/media/sdcard"
[D] unknown:0 - Storage: "Internal storage" "/home/nemo"
[D] unknown:0 - Storage: "8951-E23A" "/media/sdcard/8951-E23A"
harbour-advanced-camera: /usr/share/droidmedia/hybris.c:53: __resolve_sym: Assertion `ptr != NULL' failed.
Keskeytetty (core dumped)"

Hardware: Sony Xperia 10 with Sailfish X
OS: Suomenlinna

**Comment by henning-schild** [comment]
> Hardware: Sony Xperia 10 with Sailfish X OS: Suomenlinna

Not a "10 Compact"? If the "real" supported device is affected by that as well, upstream will be the right place to report the problem.

**Comment by henning-schild** [comment]
btw i never had that camera problem on the most recent version, but had to re-install at a point where i installed the latest android via sony emma

**Comment by henning-schild** [comment]
Now i am on a "10 II" ... size sucks, but performance and official support plus more recent android seem worth it

**Comment by smatkovi** [comment]
I've also got a 10 ii now. i Love the  oled screen and Android support and An official port

**Comment by henning-schild** [comment]
Yes, but let us stick to the topic. The "X compact" was a great device and i am happy to hang around and pledge for it and this repo.

**Comment by smatkovi** [comment]
jolla admitted that it was a bug that the camera wasn't working and effected more devices upgrading to 4.x. there was a workaround from them reinstalling some programs. if i get the time i will post it here
