### ISSUE TITLE
SFOS 3?

### ISSUE THREAD

**Issue by martonmiklos** [g7/sailfishx-patcher-f5321#3]
Hi @g7,

I am planning to get an Xperia Compact for SFOS usage.
Do you have any experience with the SFOS 3 and this compatibility layer?

Thanks in advance!

**Comment by Kabouik** [comment]
Interested as well, I'm on the verge of buying an X Compact, my Jolla C needs some rest.

**Comment by Kabouik** [comment]
Confirmed to work on TMO: https://talk.maemo.org/showpost.php?p=1550330&postcount=100

Great news, thanks @g7!

**Comment by g7** [comment]
Hello!

I haven't tried yet patching 3.0.0.x images, but I can confirm that the OTA upgrade from an older version works fine :)

**Comment by g7** [comment]
FYI - 3.0.0.8 patched successfully, haven't tried it yet but I'm pretty sure it should work as expected.

Closing this - feel free to reopen if needed.

**Comment by Kabouik** [comment]
I can confirm it works, I installed the patched 3.0.0.8 on my new X Compact yesterday. Posted about it on TMO too. I got a few errors with some repositories during the patching process but it seems there were no consequences. 

Thank you very much @g7, this is wonderful.

**Comment by g7** [comment]
Nice! Glad that it works fine. The repository refresh errors (on adaptation0, adaptation1, sailfish-eas, aliendalvik and xt9) are normal as those repositories require authentication via the Jolla Store (that's also why you can't do OTA upgrades and install the licensed bits if you don't login with the Jolla Account).
