### ISSUE TITLE
update to 3.0.3.9 worked for me

### ISSUE THREAD

**Issue by henning-schild** [g7/sailfishx-patcher-f5321#8]
I guess once the "clean patch" is tested the README can be updates. Just opening the issue to let others know that it could be safe to update ;)

**Comment by henning-schild** [comment]
also 3.0.3.10 worked without a problem

**Comment by henning-schild** [comment]
3.1.0.11 worked as well

**Comment by g7** [comment]
Thanks for the feedback :) I have updated the README to match this and 3.2.0
